### PR TITLE
fix: Remove non-exist fields from method signature in sequence.proto

### PR DESCRIPTION
**Pull request by blakeli0**
The Java GAPIC generator fails with the latest showcase protos because the method signature for `AttemptStreamingSequence` contains non-exist fields from `AttemptStreamingSequenceRequest`

To prevent this from happening in the future, is it possible to set up `api-linter` or even similar presubmit checks as what we have in googe3?

### CODE REVIEW

**Comment by noahdietz** [comment]
> To prevent this from happening in the future, is it possible to set up api-linter or even similar presubmit checks as what we have in googe3?

Probably a good idea...

**Review by noahdietz — APPROVED** [review]
Thanks for catching this.

**Comment by noahdietz** [comment]
https://www.githubstatus.com

GitHub is having an incident. github actions are just failing for no reason, so they need to be rerun. This has happened on other repos.

**Comment by blakeli0** [comment]
> https://www.githubstatus.com
> 
> GitHub is having an incident. github actions are just failing for no reason, so they need to be rerun. This has happened on other repos.

Thanks, I'll rerun failed tests and keep an eye on them

**Pull request merged**
