### PR TITLE
Utility Commands Cleanup

### PR DESCRIPTION
**Pull request by landrito**
This PR cleans up the functionality of the utils folder by doing the following:

- Consolidates the generation of the CLI, Client, and generated protos into util/cmd/compile_protos.go
- Moves the publishing of github resources and pushing the docker image from the circle config to the release script.
- Makes all util files no longer rely on the GOPATH env variable

### CODE REVIEW

**Comment by noahdietz** [comment]
LGTM but to be clear, this removes the automation of releases entirely? Someone needs to run the release script now?

**Comment by landrito** [comment]
Correct. This is essentially the status quo since the releasing to github and gcr.io through circle would require us to store github tokens and gcr tokens on circle, which I think is bad practice.

**Comment by landrito** [comment]
Essentially the release flow would be:

1. go run util/cmd/bump_version/main.go --patch
1. PR with changelog
1. go run util/cmd/release/main.go
1. update release notes with changelog (ideally the prior step would grab the latest info from the changelog)

**Comment by landrito** [comment]
Sorry to be more clear, Automated releasing through circle has never worked since someone on the team pointed out that storing github tokens on circle was a bad idea.

**Comment by landrito** [comment]
Redoing this in separate PRs.

**Pull request closed without merging**
