### PR TITLE
chore: pin Go version in Ci

### PR DESCRIPTION
**Pull request by noahdietz**

### CODE REVIEW

**Review by vchudnov-g — COMMENTED** [review]
Why pin the version as opposed to specifying a minimum version? Go make backwards-compatibility guarantees, right?

**Comment by noahdietz** [comment]
> Go make backwards-compatibility guarantees, right?

Well, yes, except there was a change in the `go` tool that caused any command that builds the code to return an error if an adjustment to the go.mod is necessary. https://golang.org/doc/go1.16#go-command:

> Build commands like go build and go test no longer modify go.mod and go.sum by default. Instead, they report an error if a module requirement or checksum needs to be added or updated (as if the -mod=readonly flag were used). Module requirements and sums may be adjusted with go mod tidy or go get.

> Why pin the version as opposed to specifying a minimum version? 

Well it was setting a floor, but then it upgraded to this latest version and started reporting errors on some `go` commands. This is rather annoying and I can see this being an issue in the future with generated code changes.

**Review by vchudnov-g — APPROVED** [review]
Sigh. It's mildly annoying we have to pin it rather than floor it, but looks like we need it.

**Comment by noahdietz** [comment]
> Sigh. It's mildly annoying we have to pin it rather than floor it, but looks like we need it.

I agree. We can change it in the future.

**Pull request merged**
