### PR TITLE
feat: Enforce checking for optional field presence/absence in test suite requests

### PR DESCRIPTION
**Pull request by vchudnov-g**
**Note** that this uses the `embed` package, which requires a switch to Go 1.16.

The `compliance_suite.json` file is moved from its old location under `schema/` to a location under `server` because `embed` does not follow symlinks. The original location under `schema/` becomes a symlink to the new location so that we may continue easily releasing the suite with other `schema/` files.

### CODE REVIEW

**Comment by noahdietz** [comment]
> **Note** that this uses the `embed` package, which requires a switch to Go 1.16.

You will need to update the version of Go used in all GitHub Actions.

**Comment by vchudnov-g** [comment]
Update the Go version in a bunch places. Have I missed any?

**Comment by noahdietz** [comment]
> Update the Go version in a bunch places. Have I missed any?

lgtm! we will find out if we missed some ;)

**Comment by noahdietz** [comment]
Looks like there was a linter violation. You can check the linter results from the Actions UI, and you'll find the "Artifacts" dropdown in the top right has a `linting-results` file.

**Comment by vchudnov-g** [comment]
Oops, missed that! Should be fixed now.

**Comment by vchudnov-g** [comment]
I'll add some tests to bring the coverage back up, but please do start reviewing. ;-)

**Review by noahdietz — APPROVED** [review]
lgtm once you get the added coverage :)

**Comment by vchudnov-g** [comment]
Yay! I got the code coverage up to 100% on this patch!

**Pull request merged**
